name: deepclean-base
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - gwpy=2.1.5
  - astropy
  - python-ldas-tools-framecpp<3.0.0
  - python-nds2-client
  - pytorch=1.13.1
  - torchvision
  - cudatoolkit=11.3
