[tool.pinto]
steps = [
    "train:train:autoencoder",
    "export:export-model:autoencoder",
    "infer:infer",
    "analyze:analyze"
]

[tool.typeo.base]
channels = [
    "H1:GDS-CALIB_STRAIN",
    "H1:PEM-CS_MAINSMON_EBAY_1_DQ",
    "H1:ASC-INP1_P_INMON",
    "H1:ASC-INP1_Y_INMON",
    "H1:ASC-MICH_P_INMON",
    "H1:ASC-MICH_Y_INMON",
    "H1:ASC-PRC1_P_INMON",
    "H1:ASC-PRC1_Y_INMON",
    "H1:ASC-PRC2_P_INMON",
    "H1:ASC-PRC2_Y_INMON",
    "H1:ASC-SRC1_P_INMON",
    "H1:ASC-SRC1_Y_INMON",
    "H1:ASC-SRC2_P_INMON",
    "H1:ASC-SRC2_Y_INMON",
    "H1:ASC-DHARD_P_INMON",
    "H1:ASC-DHARD_Y_INMON",
    "H1:ASC-CHARD_P_INMON",
    "H1:ASC-CHARD_Y_INMON",
    "H1:ASC-DSOFT_P_INMON",
    "H1:ASC-DSOFT_Y_INMON",
    "H1:ASC-CSOFT_P_INMON",
    "H1:ASC-CSOFT_Y_INMON"
]
sample_rate = 4096
verbose = false

train_t0 = 1251335314
train_duration = 4096

infer_kernel_length = 1
infer_batch_size = 64
inference_sampling_rate = 512

test_t0 = 1251339410
test_duration = 16384

max_latency = 0.5
freq_low = 55
freq_high = 65

# we can leave the autoencoder args empty because
# it doesn't take any arguments except input shape
autoencoder = {}

[tool.typeo.scripts.train]
# paths
output_directory = "${PROJECT_DIR}"
data_directory = "${DATA_DIR}"

# data parameters
channels = "${base.channels}"
t0 = "${base.train_t0}"
duration = "${base.train_duration}"
valid_frac = 0.25

# data loading parameters
sample_rate = "${base.sample_rate}"
kernel_length = 8
kernel_stride = 0.0625

# preprocessing parameters
freq_low = "${base.freq_low}"
freq_high = "${base.freq_high}"
filter_order = 8

# optimization parameters
batch_size = 256
max_epochs = 500
lr = 3.2e-2
weight_decay = 1e-5
patience = 8
factor = 0.2
early_stop = 50

# criterion parameters
fftlength = 2
overlap = 1
alpha = 1.0

# miscellaneous parameters
device = "cuda"
profile = false
verbose = "${base.verbose}"

# architecture subcommands
commands.autoencoder = "${base.autoencoder}"

[tool.typeo.scripts.export-model]
repository_directory = "${MODEL_REPOSITORY}"
output_directory = "${PROJECT_DIR}"
channels = "${base.channels}"
kernel_length = "${base.infer_kernel_length}"
sample_rate = "${base.sample_rate}"
inference_sampling_rate = "${base.inference_sampling_rate}"
batch_size = "${base.infer_batch_size}"
max_latency = [0.25, 0.5, 0.75]
instances = 6
verbose = "${base.verbose}"
commands.autoencoder = "${base.autoencoder}"

[tool.typeo.scripts.infer]
url = "localhost:8001"
model_name = "deepclean-stream-${base.max_latency}"

output_directory = "${PROJECT_DIR}"
model_repo_dir = "${MODEL_REPOSITORY}"
data_path = "${DATA_DIR}"

t0 = "${base.test_t0}"
duration = "${base.test_duration}"
channels = "${base.channels}"
kernel_length = "${base.infer_kernel_length}"
inference_sampling_rate = "${base.inference_sampling_rate}"
inference_rate = 256
sample_rate = "${base.sample_rate}"
batch_size = "${base.infer_batch_size}"
freq_low = "${base.freq_low}"
freq_high = "${base.freq_high}"

max_latency = "${base.max_latency}"
memory = 10
look_ahead = 0.5

gpus = [0]
sequence_id = 1001
verbose = "${base.verbose}"

[tool.typeo.scripts.analyze]
raw_data_path = "${DATA_DIR}"
clean_data_dir = "${PROJECT_DIR}/cleaned"
output_directory = "${PROJECT_DIR}"

channels = "${base.channels}"
t0 = "${base.test_t0}"
duration = 4097
sample_rate = "${base.sample_rate}"
window_length = 60
fftlength = 10

freq_low = "${base.freq_low}"
freq_high = "${base.freq_high}"
