name: ci-tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # tests the libraries that our projects depend on
  library-ci-tests:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    container:
      image: ghcr.io/ml4gw/pinto:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      volumes:
        - ${{ github.workspace }}:/github/workspace
    strategy:
      matrix:
        lib: [architectures, signal, export, gwftools, trainer, infer]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: run ${{ matrix.lib }} tests
        env:
          test_dir: /github/workspace/libs/${{ matrix.lib }}
        run: pinto -p $test_dir run pytest $test_dir/tests -x

  # if all the libraries pass, tests the projects
  # that depend on them
  project-ci-tests:
    needs: library-ci-tests
    runs-on: ubuntu-latest
    permissions:
      packages: read
    container:
      image: ghcr.io/ml4gw/pinto:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      volumes:
        - ${{ github.workspace }}:/github/workspace
    strategy:
      matrix:
        project: [sandbox/train]
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: recursive
      -
        name: run ${{ matrix.project }} tests
        env:
          test_dir: /github/workspace/projects/${{ matrix.project }}
        run: pinto -p $test_dir run pytest $test_dir/tests -x
